name: Build and publish

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TYPESENSE_HOST: typesense.acdh-dev.oeaw.ac.at
      TYPESENSE_PORT: 443
      TYPESENSE_PROTOCOL: https
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install Saxon, Ant and Fundament
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./script.sh
    - name: Install Ant-Contrib
      run: |
        wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
        mv ant-contrib-1.0b3.jar /usr/share/ant/lib
    - name: Python
      run: |
        pip install -r requirements.txt
    - name: Fetch the Data
      run: |
        ./fetch_data.sh
    - name: Build
      run: |
        ant
    - name: create typesense index
      run: |
        python make_ts_index.py
    - name: Copy processed data to freud-digital/frd-archiv
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './data/.'
        destination_repo: 'freud-digital/frd-archiv'
        destination_folder: 'data'
        user_email: 'peter.andorfer@oeaw.ac.at.com'
        user_name: 'csae8092'
        commit_message: 'copy XML/TEI files from frd-static'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html